#!/usr/bin/env bash
# publish-formulae.sh — render the pindex + pindex-lite Homebrew formulae from
# release tarballs and push them to the jjfantini/homebrew-humbl tap.
#
# Why this exists: OSS goreleaser cannot package the cgo `pindex` binary (the
# `prebuilt` builder is Pro-only), and goreleaser deprecated `brews` in favour of
# macOS-only `homebrew_casks` (which would drop Linux). So both formulae are
# templated here — one consistent mechanism, full macOS + Linux support.
#
# Usage:
#   VERSION=0.1.0 DIST_DIR=dist publish-formulae.sh            # clone tap + push
#   VERSION=0.1.0 DIST_DIR=dist DRY_RUN=1 OUT_DIR=/tmp/f \      # render only
#     publish-formulae.sh
#
# Inputs (env):
#   VERSION             release version, no leading v (e.g. 0.1.0)   [required]
#   DIST_DIR            dir holding the 8 *.tar.gz release archives  [default: dist]
#   HOMEBREW_TAP_TOKEN  PAT with contents:write on homebrew-humbl    [required unless DRY_RUN]
#   DRY_RUN             if set, render formulae to OUT_DIR, no clone/push
#   OUT_DIR             where DRY_RUN writes the .rb files           [default: ./_formulae]
#   TAP_OWNER/TAP_REPO  tap location          [default: jjfantini / homebrew-humbl]
#   FORMULA_DIR         dir inside the tap for formulae              [default: Formula]
set -euo pipefail

VERSION="${VERSION:?set VERSION (no leading v, e.g. 0.1.0)}"
DIST_DIR="${DIST_DIR:-dist}"
TAP_OWNER="${TAP_OWNER:-jjfantini}"
TAP_REPO="${TAP_REPO:-homebrew-humbl}"
FORMULA_DIR="${FORMULA_DIR:-Formula}"
REPO="jjfantini/pindex"
BASE_URL="https://github.com/${REPO}/releases/download/v${VERSION}"

sha256() { # portable sha256 of a file -> hex
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

require_tarball() {
  [ -f "$1" ] || { echo "ERROR: missing release archive: $1" >&2; exit 1; }
}

# emit_formula <ClassName> <binary> <archive_prefix> <license> <desc> [caveats]
emit_formula() {
  local klass="$1" binary="$2" prefix="$3" license="$4" desc="$5" caveats="${6:-}"
  local da="${DIST_DIR}/${prefix}_${VERSION}_darwin_arm64.tar.gz"
  local dx="${DIST_DIR}/${prefix}_${VERSION}_darwin_amd64.tar.gz"
  local la="${DIST_DIR}/${prefix}_${VERSION}_linux_arm64.tar.gz"
  local lx="${DIST_DIR}/${prefix}_${VERSION}_linux_amd64.tar.gz"
  require_tarball "$da"; require_tarball "$dx"
  require_tarball "$la"; require_tarball "$lx"

  cat <<RUBY
# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class ${klass} < Formula
  desc "${desc}"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "${license}"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/${prefix}_${VERSION}_darwin_arm64.tar.gz"
      sha256 "$(sha256 "$da")"
    else
      url "${BASE_URL}/${prefix}_${VERSION}_darwin_amd64.tar.gz"
      sha256 "$(sha256 "$dx")"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE_URL}/${prefix}_${VERSION}_linux_arm64.tar.gz"
      sha256 "$(sha256 "$la")"
    else
      url "${BASE_URL}/${prefix}_${VERSION}_linux_amd64.tar.gz"
      sha256 "$(sha256 "$lx")"
    end
  end

  def install
    bin.install "${binary}"
  end
$( [ -n "$caveats" ] && printf '\n  def caveats\n    <<~EOS\n%s\n    EOS\n  end\n' "$(printf '%s\n' "$caveats" | sed 's/^/      /')" )
  test do
    system "#{bin}/${binary}", "--version"
  end
end
RUBY
}

PINDEX_DESC="Vectorless reasoning-RAG engine in Go — hierarchical tree index over PDFs, cited answers"
LITE_DESC="pindex (pure-Go, portable build — Apache-2.0, no MuPDF/cgo)"
LITE_CAVEATS="pindex-lite is the pure-Go build with no MuPDF extractor compiled in.
Set \`extractor: purego\` in your pindex config; the \`mupdf\` backend is
unavailable in this build (it returns a clear error if selected)."

render() {
  local dir="$1"
  mkdir -p "$dir"
  emit_formula "Pindex"     "pindex"      "pindex"      "AGPL-3.0-or-later" "$PINDEX_DESC"              > "${dir}/pindex.rb"
  emit_formula "PindexLite" "pindex-lite" "pindex-lite" "Apache-2.0"        "$LITE_DESC" "$LITE_CAVEATS" > "${dir}/pindex-lite.rb"
  echo "rendered ${dir}/pindex.rb and ${dir}/pindex-lite.rb"
}

if [ -n "${DRY_RUN:-}" ]; then
  render "${OUT_DIR:-./_formulae}"
  exit 0
fi

: "${HOMEBREW_TAP_TOKEN:?set HOMEBREW_TAP_TOKEN (or DRY_RUN=1)}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
git clone --depth 1 "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${TAP_OWNER}/${TAP_REPO}.git" "$work/tap"
render "$work/tap/${FORMULA_DIR}"
cd "$work/tap"
git config user.name "humbl-release-bot"
git config user.email "release-bot@users.noreply.github.com"
git add "${FORMULA_DIR}/pindex.rb" "${FORMULA_DIR}/pindex-lite.rb"
if git diff --cached --quiet; then
  echo "no formula changes to push"
else
  git commit -m "pindex ${VERSION}: update pindex + pindex-lite formulae"
  git push
  echo "pushed pindex ${VERSION} formulae to ${TAP_OWNER}/${TAP_REPO}"
fi
